version: "3.3"
services:
  master:
    build:
      context: ./
      dockerfile: dockerfile-spark
    hostname: spark-master
    ports:
      - "8088:8088"
      - "7077:7077"
    environment:
      - "SPARK_LOCAL_IP=spark-master"
      - "SPARK_MASTER_PORT=7077"
      - "SPARK_MASTER_WEBUI_PORT=8088"
    command: "/start-spark-master.sh"
    image: spark-master
  worker:
    image: spark-master
    depends_on:
      - spark-master
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_WEBUI_PORT=8088"
    command: "/start-spark-worker.sh"
  consumer:
    image: spark-master
    depends_on:
      - spark-master
    restart: unless-stopped
    volumes:
      - ./consumer/:/consumer
    command: python consumer/main.py
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${DOCKER_KAFKA_HOST}
      KAFKA_CREATE_TOPICS: "example:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"
  monitor:
    build: ./monitor
    command: uvicorn monitor.app.main:app --reload --workers 1 --host 0.0.0.0 --port 8501
    volumes:
        - ./monitor/:/usr/src/monitor
    ports:
        - 8501:8501
    image: oetkertor:latest
